services:
  api-gateway:  # Cambiato da "app" a "api-gateway"
    build:
      context: ./api-gateway  # Cartella di build per api-gateway
      dockerfile: Dockerfile  # Specifica il Dockerfile nella cartella api-gateway
    container_name: api-gateway-image
    ports:
      - "8000:8000"
    depends_on:
      mongo: 
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/3dgs_models
      - RABBITMQ_HOSTNAME=rabbitmq  # HOST RabbitMQ
      - RABBITMQ_PORT=5672  # HOST RabbitMQ
      - RABBITMQ_USER=${RABBIT_MQ_USER_WRITER}
      - RABBITMQ_PASS=${RABBIT_MQ_PASS_WRITER}
    networks:
      - my_network

  job-executor:
    build:
      context: ./job-executor
      dockerfile: Dockerfile  # Dockerfile per job-executor
    container_name: job-executor-image
    depends_on:
      mongo: 
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - shared_data:${MODEL_WORKING_DIR}   # Stesso volume condiviso
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - MONGO_URI=mongodb://mongo:27017/3dgs_models
      - RABBITMQ_HOSTNAME=rabbitmq  # HOST RabbitMQ
      - RABBITMQ_PORT=5672  # HOST RabbitMQ
      - RABBITMQ_USER=${RABBIT_MQ_USER_READER}
      - RABBITMQ_PASS=${RABBIT_MQ_PASS_READER}
      - MODEL_WORKING_DIR=${MODEL_WORKING_DIR}
    restart: always
    networks:
      - my_network
  gaussian-splatting-base:  # Cambiato da "app" a "api-gateway"
    build:
      context: ./gaussian-splatting  # Cartella di build per api-gateway
      dockerfile: Dockerfile.base  # Usa Dockerfile.base per costruire l'immagin
    container_name: gaussian-splatting-base-image
    image: gaussian-splatting-base  # 👈 Aggiungi questa riga
    networks:
      - my_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Usa tutte le GPU disponibili
              capabilities: [gpu]

  gaussian-splatting-api:
    build:
      context: ./gaussian-splatting  # Nuovo servizio API per Gaussian Splatting
      dockerfile: Dockerfile
    container_name: gaussian-splatting-api-image
    volumes:
      - shared_data:${MODEL_WORKING_DIR}   # Stesso volume condiviso
      - /tmp/.X11-unix:/tmp/.X11-unix  # Monta il socket X11
    ports:
      - "8050:8050"  # Espone l'API sulla porta 8050
    depends_on:
      - gaussian-splatting-base
    environment:
      - MODEL_WORKING_DIR=/app/shared_data
      - GAUSSIAN_SPLATTING_HOST=gaussian-splatting
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - DISPLAY=${DISPLAY}  # Usa il DISPLAY del sistema host
    networks:
    - my_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Usa tutte le GPU disponibili
              capabilities: [gpu]
  mongo:
    image: mongo
    container_name: mongo-image
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Aggiungi il volume persistente per MongoDB
    networks:
      - my_network
    environment:
      - MONGO_INITDB_DATABASE=3d_gaussian_splatting

  rabbitmq:
    image: "rabbitmq:3-management"  # Usa l'immagine RabbitMQ con interfaccia di gestione
    container_name: rabbitmq-image
    hostname: 3dgs-job-queue    
    ports:
      - "15672:15672"  # Interfaccia di gestione RabbitMQ
      - "5672:5672"    # Porta di comunicazione AMQP (RabbitMQ)
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/  # Aggiungi il volume persistente per Rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json  # Monta il file definitions.json direttamente
    networks:
      - my_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_DEFAULT_PASS}
    command: >
      bash -c "rabbitmq-server & 
               until rabbitmqctl await_startup; do sleep 1; done; 
               rabbitmqctl import_definitions /etc/rabbitmq/definitions.json; 
               tail -f /dev/null"

volumes:
  mongodb_data:  # Definisce il volume del db
    driver: local
  rabbitmq_data:  # Definisce il volume della coda di messaggi
    driver: local 
  shared_data:  # Definisce il volume condiviso tra job-executor e gaussian-splatting
    driver: local

networks:
  my_network:
    driver: bridge


