version: '3.8'

services:
  api-gateway:  # Cambiato da "app" a "api-gateway"
    build:
      context: ./api-gateway  # Cartella di build per api-gateway
      dockerfile: Dockerfile  # Specifica il Dockerfile nella cartella api-gateway
    container_name: api-gateway-image
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/my_database
    networks:
      - my_network

  mongo:
    image: mongo
    container_name: mongo-image
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Aggiungi il volume persistente per MongoDB
    networks:
      - my_network
    environment:
      - MONGO_INITDB_DATABASE=3d_gaussian_splatting

  gaussian-splatting:  # Cambiato da "app" a "api-gateway"
    build:
      context: ./gaussian-splatting  # Cartella di build per api-gateway
      dockerfile: Dockerfile  # Specifica il Dockerfile nella cartella api-gateway
    container_name: gaussian-splatting-image
    networks:
      - my_network



volumes:
  mongodb_data:  # Definisce il volume persistente
    driver: local

networks:
  my_network:
    driver: bridge
